#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 server
# Configures HAproxy to send traffic to web-01 and web-02 using roundrobin

# Update package list and install HAproxy
apt-get update
apt-get install -y haproxy

# Enable HAproxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup original configuration
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAproxy
cat > /etc/haproxy/haproxy.cfg << 'INNER_EOF'
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6784-web-01 98.81.230.90:80 check
    server 6784-web-02 3.86.95.86:80 check
INNER_EOF

# Restart HAproxy to apply changes
service haproxy restart
