#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Backup original config
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add configurations after server_name line
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t}' /etc/nginx/sites-available/default

service nginx restart
